# A simple name for your workflow
name: IITM Student ID Check

# Controls when the action will run. 
# 'push' means it runs when you commit changes to the main branch.
# 'workflow_dispatch' allows you to run it manually from the Actions tab.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # This is the specific step required by your assignment
      - name: 23F2003965@ds.study.iitm.ac.in
        run: echo "Hello, World! This step is correctly named."
